spin_manifest_version = 2

[application]
name = "santa"
version = "0.1.0"
authors = ["chicoxyzzy <chi187@gmail.com>"]
description = ""

[[trigger.http]]
route = "/api/..."
component = "api"

[component.api]
source = "api/main.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.api.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "api"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/..."
component = "web"

[component.web]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "static", destination = "/" }]
